version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./custom.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
  app1:
    image: nginx:latest
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./app1:/app
  app2:
    image: nginx:latest
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf 
      - ./app2:/app 
