Description: Opsinator

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: resi-buy-gradproject-bharg-sg
      GroupDescription: "Enable SSH access, HTTP, HTTPS and ICMP access"
      VpcId: "vpc-08bb37391caa055ec"
      SecurityGroupIngress:
        -
          Description: "Allow access via SSH on port 22 only through REA Melbourne office"
          FromPort: 22
          ToPort: 22
          IpProtocol: "tcp"
          CidrIp: 
        -
          Description: "Allow everyone access via HTTP on port 80"
          FromPort: 80
          ToPort: 80
          IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
        -
          Description: "Allow everyone access via HTTPS on port 443"
          FromPort: 443
          ToPort: 443
          IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
        -
          Description: "Allow everyone access via ICMP on port 8"
          FromPort: 8
          ToPort: -1 #allows any icmp request
          IpProtocol: "icmp"
          CidrIp: "0.0.0.0/0"